//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamOn.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExamOn_DummyEntities : DbContext
    {
        public ExamOn_DummyEntities()
            : base("name=ExamOn_DummyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblactivityHistory> tblactivityHistories { get; set; }
        public virtual DbSet<tblAnswer> tblAnswers { get; set; }
        public virtual DbSet<tblBatch> tblBatches { get; set; }
        public virtual DbSet<tblClass> tblClasses { get; set; }
        public virtual DbSet<tblEmailCrediential> tblEmailCredientials { get; set; }
        public virtual DbSet<tblexam> tblexams { get; set; }
        public virtual DbSet<tblexamLive> tblexamLives { get; set; }
        public virtual DbSet<tblexamQuestion> tblexamQuestions { get; set; }
        public virtual DbSet<tblexamSection> tblexamSections { get; set; }
        public virtual DbSet<tblexamStudent> tblexamStudents { get; set; }
        public virtual DbSet<tbllogin> tbllogins { get; set; }
        public virtual DbSet<tblloginType> tblloginTypes { get; set; }
        public virtual DbSet<tblQuestion> tblQuestions { get; set; }
        public virtual DbSet<tblSection> tblSections { get; set; }
        public virtual DbSet<tblshift> tblshifts { get; set; }
        public virtual DbSet<tbltenant> tbltenants { get; set; }
        public virtual DbSet<tbluserProfile> tbluserProfiles { get; set; }
    }
}
