//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamOn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblactivityHistory
    {
        public long id { get; set; }
        public string Activity { get; set; }
        public string Module { get; set; }
        public System.DateTime createdate { get; set; }
        public long UserId { get; set; }
    
        public virtual tbllogin tbllogin { get; set; }
    }
}
