//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamOn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBatch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblBatch()
        {
            this.tblshifts = new HashSet<tblshift>();
        }
    
        public long id { get; set; }
        public string Batch { get; set; }
        public long Class { get; set; }
        public bool Active { get; set; }
    
        public virtual tblClass tblClass { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblshift> tblshifts { get; set; }
    }
}
