//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamOn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblexamSection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblexamSection()
        {
            this.tblexamQuestions = new HashSet<tblexamQuestion>();
        }
    
        public long id { get; set; }
        public long Exam { get; set; }
        public long Sections { get; set; }
        public bool Active { get; set; }
    
        public virtual tblexam tblexam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblexamQuestion> tblexamQuestions { get; set; }
        public virtual tblSection tblSection { get; set; }
    }
}
