//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamOn.Models
{
    using ExamOn.DataLayer;
    using System;
    using System.Collections.Generic;
    
    public partial class tblexam :GenericModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblexam()
        {
            this.tblexamLives = new HashSet<tblexamLive>();
            this.tblexamSections = new HashSet<tblexamSection>();
            this.tblexamStudents = new HashSet<tblexamStudent>();
        }
    
        public long id { get; set; }
        public string ExamName { get; set; }
        public string Instructions { get; set; }
        public System.DateTime StartExam { get; set; }
        public System.DateTime EndExam { get; set; }
        public System.DateTime EntryAllowedTill { get; set; }
        public bool KeyBoardBlock { get; set; }
        public bool FullScreen { get; set; }
        public bool ResultAfterExam { get; set; }
        public bool ReviewAfterExam { get; set; }
        public bool Active { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public Nullable<long> SetByUserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblexamLive> tblexamLives { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblexamSection> tblexamSections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblexamStudent> tblexamStudents { get; set; }
        public virtual tbllogin tbllogin { get; set; }
    }
}
