//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamOn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblexamLive
    {
        public long id { get; set; }
        public long Exam { get; set; }
        public long Question { get; set; }
        public Nullable<int> ChoosedOption { get; set; }
        public string TimeTaken { get; set; }
    
        public virtual tblexam tblexam { get; set; }
        public virtual tblQuestion tblQuestion { get; set; }
    }
}
