//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamOn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbllogin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbllogin()
        {
            this.tblactivityHistories = new HashSet<tblactivityHistory>();
            this.tblexamStudents = new HashSet<tblexamStudent>();
        }
    
        public long id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string EmailId { get; set; }
        public string Mobile { get; set; }
        public bool Active { get; set; }
        public Nullable<bool> BlockLogin { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string TenantToken { get; set; }
        public byte[] BlockMessage { get; set; }
        public int LoginType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblactivityHistory> tblactivityHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblexamStudent> tblexamStudents { get; set; }
        public virtual tblloginType tblloginType { get; set; }
        public virtual tbltenant tbltenant { get; set; }
    }
}
