//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamOn.Models
{
    using ExamOn.DataLayer;
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudentEnrollmentSignUp : GenericModel
    {
        public long id { get; set; }
        public string TenantId { get; set; }
        public string ProfileName { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string EnrollmentNumber { get; set; }
        public bool IsHighSchool { get; set; }
        public Nullable<int> HighSchoolPercentageCGPA { get; set; }
        public bool IsInter { get; set; }
        public Nullable<int> InterPercentageCGPA { get; set; }
        public string HighSchoolCollege { get; set; }
        public string InterCollege { get; set; }
        public bool IsGraduate { get; set; }
        public Nullable<int> GradutePercentageCGPA { get; set; }
        public string GraduateCollege { get; set; }
        public bool IsPostGradute { get; set; }
        public Nullable<int> PostGradutePercentageCGPA { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int InterestedInShift { get; set; }
    
        public virtual tbltenant tbltenant { get; set; }
    }
}
