//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamOn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbltenant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbltenant()
        {
            this.tbllogins = new HashSet<tbllogin>();
        }
    
        public string id { get; set; }
        public string TenantName { get; set; }
        public string TenantAddress { get; set; }
        public string TenantEmail { get; set; }
        public string TenantMobile { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime SubscriptionEndDate { get; set; }
        public string SubscriptionEndMessage { get; set; }
        public System.DateTime LastRechargeOn { get; set; }
        public long RechargeAmount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbllogin> tbllogins { get; set; }
    }
}
