//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamOn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTenantRechargeHistory
    {
        public long id { get; set; }
        public System.DateTime SubscptionStartFrom { get; set; }
        public System.DateTime SubscriptionEndAt { get; set; }
        public double RechargeAmount { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string TID { get; set; }
    }
}
