//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamOn.Models
{
    using ExamOn.DataLayer;
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserShift : GenericModel
    {
        public long id { get; set; }
        public long UserId { get; set; }
        public long ShiftId { get; set; }
        public bool Active { get; set; }
    
        public virtual tblshift tblshift { get; set; }
        public virtual tbluserProfile tbluserProfile { get; set; }
    }
}
