//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamOn.Models
{
    using ExamOn.DataLayer;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class tbluserProfile : GenericModel
    {
        public long id { get; set; }
        public string UserName { get; set; }
        public string address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<long> Shift { get; set; }
        public string RealName { get; set; }
    
        public virtual tblshift tblshift { get; set; }

        [NotMapped]
        public Nullable<int> LoginType { get; set; }

        [NotMapped]
        public string LoginTypeName { get; set; }
    }
}
